#!/bin/bash
echo "(Mission Briefer): We have another new mission for you."
echo "(Mission Briefer): Here is what you need to do (What you need to do)"
echo "(Mission Briefer): In order to complete the assignment, you'll need this."
echo "------------CAT SKILL AQUIRED--------------"
echo "| Allows user to output contents of a file |"
echo "|     Use by typing: cat (filename)        |"
echo "|     To append files together use:        |"
echo "|          cat (file1) >> (file2)          |"
echo "--------------------------------------------" 
echo "(Mission Briefer): Now, go to the training area, you will need some practice."
